# @package _group_
kwargs:
  gpus: -1
  accelerator: ddp
  max_epochs: 5 #40
  gradient_clip_val: 1
  log_gpu_memory: None  # set to min_max or all for debug
  precision: 32
  terminate_on_nan: False
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 8
  replace_sampler_ddp: False

checkpoint_kwargs:
  save_top_k: -1
