indir: ../dataset/AnimatedDrawings/preprocessed
uid_json: ../dataset/AnimatedDrawings/drawings_uids.json

model:
  # pix2pixhd
  # path: ./experiments/contour_removal_2024-05-12_01-09-04_train_lama-regular.yaml_
  # checkpoint: epoch=3-step=3599.ckpt

  # FFC-ResNet
  path: ./experiments/contour_removal_2024-05-12_02-43-10_train_lama-fourier.yaml_
  checkpoint: epoch=3-step=3599.ckpt

dataset:
  kind: default

device: cuda

